"""Add density field to MetalGrade with default value

Revision ID: 75aa6b07855e
Revises: 
Create Date: 2024-11-27 20:31:40.995597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75aa6b07855e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('metal_grade', schema=None) as batch_op:
        # Сначала добавляем колонку как nullable
        batch_op.add_column(sa.Column('density', sa.Float(), nullable=True))
        
    # Обновляем существующие записи значением по умолчанию
    op.execute('UPDATE metal_grade SET density = 7.85')
    
    # Делаем колонку not nullable
    with op.batch_alter_table('metal_grade', schema=None) as batch_op:
        batch_op.alter_column('density',
               existing_type=sa.Float(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('metal_grade', schema=None) as batch_op:
        batch_op.drop_column('density')

    # ### end Alembic commands ###
